modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="guineapigs"
version="${file.jarVersion}"
displayName="Guinea Pig Mod"
logoFile="examplemod.png"

credits="Java, Mojang, Twins730"
authors="Twins730 & Twins037"
description='''
    Adds adorable guinea pigs to minecraft!
'''
# dependencies
[[dependencies.guineapigs]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.guineapigs]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
